// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdbConnect(arg1) {
  return window['go']['main']['App']['AdbConnect'](arg1);
}

export function AdbDevices() {
  return window['go']['main']['App']['AdbDevices']();
}

export function AdbDisconnect(arg1) {
  return window['go']['main']['App']['AdbDisconnect'](arg1);
}

export function AdbPair(arg1, arg2) {
  return window['go']['main']['App']['AdbPair'](arg1, arg2);
}

export function AdbVersion() {
  return window['go']['main']['App']['AdbVersion']();
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function DeleteSnippet(arg1) {
  return window['go']['main']['App']['DeleteSnippet'](arg1);
}

export function ForgetPairings() {
  return window['go']['main']['App']['ForgetPairings']();
}

export function GetAdbEndpoints() {
  return window['go']['main']['App']['GetAdbEndpoints']();
}

export function GetPairing() {
  return window['go']['main']['App']['GetPairing']();
}

export function GetSnippets() {
  return window['go']['main']['App']['GetSnippets']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ReplaceDictionary(arg1) {
  return window['go']['main']['App']['ReplaceDictionary'](arg1);
}

export function SaveCategory(arg1) {
  return window['go']['main']['App']['SaveCategory'](arg1);
}

export function SaveSnippet(arg1) {
  return window['go']['main']['App']['SaveSnippet'](arg1);
}

export function StartAdbDiscovery() {
  return window['go']['main']['App']['StartAdbDiscovery']();
}

export function StopAdbDiscovery() {
  return window['go']['main']['App']['StopAdbDiscovery']();
}
