// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adbwireless} from '../models';
import {transport} from '../models';
import {snippets} from '../models';

export function AdbConnect(arg1:string):Promise<string>;

export function AdbDevices():Promise<Array<adbwireless.Device>>;

export function AdbDisconnect(arg1:string):Promise<string>;

export function AdbPair(arg1:string,arg2:string):Promise<adbwireless.PairResult>;

export function AdbVersion():Promise<string>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteSnippet(arg1:number):Promise<void>;

export function ForgetPairings():Promise<void>;

export function GetAdbEndpoints():Promise<Array<adbwireless.Endpoint>>;

export function GetPairing():Promise<transport.PairingSnapshot>;

export function GetSnippets():Promise<snippets.Snapshot>;

export function GetStatus():Promise<transport.Status>;

export function ReplaceDictionary(arg1:Array<string>):Promise<void>;

export function SaveCategory(arg1:snippets.Category):Promise<number>;

export function SaveSnippet(arg1:snippets.Snippet):Promise<number>;

export function StartAdbDiscovery():Promise<void>;

export function StopAdbDiscovery():Promise<void>;
